---
- hosts: all
  become: true
  tasks:
  - name: Update Apt
    apt: update_cache=true
  - name: Install X Server stuff
    apt: name={{item}} state=latest
    with_items:
    - virtualbox-guest-dkms
    - xinit
    - i3
  - name: Install Apt dev tools
    apt: name={{item}} state=latest
    with_items:
    - git
    - lxterminal
    - stow
    - gdebi # this will let me install debs

    # need to create a config directory so stow doesn't create item
    # as a symlink
  - name: Create config directory
    become_user: vagrant
    file: path=~/.config/ state=directory
  - name: Git configs
    become_user: vagrant
    git: repo=https://github.com/bbkane/backup.git dest=~/backup
  - name: Stow configs
    become_user: vagrant
    command: stow ubuntu-term chdir=~/backup
  - name: Stow neovim configs
    become_user: vagrant
    command: stow neovim chdir=~/backup

  - name: Download Vs-Code
    get_url: url=https://go.microsoft.com/fwlink/?LinkID=760868 dest=/tmp/vscode.deb
  - name: Check if VS-Code is installed
    command: which code
    register: vscode_installed
    ignore_errors: true
  - name: Install VS-Code
    command: gdebi /tmp/vscode.deb -n
    when: vscode_installed|failed
  
  - name: Add Neovim Repo
    apt_repository: repo='ppa:neovim-ppa/unstable'
  - name: Install Neovim
    apt: name={{item}} update_cache=true
    with_items:
    - python3-dev
    - python3-pip
    - neovim
  - name: Install Neovim pip module
    pip: name=neovim executable=pip3
  - name: Create Neovim config directory
    become_user: vagrant
    file: path=~/.config/nvim/autoload state=directory
  - name: Install plug.vim
    become_user: vagrant
    get_url: >
      url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
      dest=~/.config/nvim/autoload/plug.vim
  - name: Update Vim
    alternatives: name=vim path=/usr/bin/nvim link=/usr/bin/vim
  - name: Update Editor
    alternatives: name=editor path=/usr/bin/nvim link=/usr/bin/editor
  # TODO: install dev tools, get and symlink configs from github with stow
  # TODO: make neovim playlist
